/*
TOPIC : UPDATING / DELETING DATA
UPDATE : IT UPDATES THE PRE EXISTED TABLE
DELETE : DELET THE ROWS WHICH YOU WANT TO
*/

SELECT *
FROM SQL_Tutorial.dbo.Employeedemographics

/* UPDATING */

UPDATE SQL_Tutorial.dbo.Employeedemographics
SET EmployeeId=1012 
WHERE FirstName='ASH' AND LastName='WALTER'

/* IT IS ADVISED TO USE A UNIQUE COLUMN OF THE TABLE LIKE EMPLOYEE ID */

UPDATE SQL_Tutorial.dbo.Employeedemographics
SET Age=34 
WHERE EmployeeId=1054

/* !!! BE VERY VERY CAUTIOUS WHILE USING DELETE STATEMENT ONCE YOU DELETE IT 
THERE IS NO WAY TO RETRIVE THE DATA */

DELETE FROM SQL_Tutorial.dbo.Employeedemographics
WHERE EmployeeId=1005

/* TO AVOID THE DELETE RELATED MISTAKES IT IS PREFERRED TO USE SELECT STATEMENT
BEFORE THE DELETE AS SHOWN BELOW */

-- STEP 1 : TO VERIFY THE ROW GOING TO BE DELETE IF IT IS CORRECT MOVE TO STEP 2

SELECT *
FROM SQL_Tutorial.dbo.Employeedemographics
WHERE EmployeeId=1006

--STEP 2 : REPLACE THE 'SELECT *' WITH DELETE KEYWORD

DELETE
FROM SQL_Tutorial.dbo.Employeedemographics
WHERE EmployeeId=1006