/*
TOPIC : SIBQUERIES
SUBQUERIES ARE OFTEN KNOWN AS NESTED QUERY OR QUERY WITHIN A QUERY
A SUB QUERY IS UESED TO RETURN DATA FROM THE MAIN QUERY OR OUTER QUERY
SUBQUEY CAN BE USED IN ANYWHWERE
*/

SELECT *
FROM Employeesalary

--SUBQUERY IN SELECT

SELECT EmoloyeeId,Salary,(SELECT AVG(SALARY) FROM Employeesalary)
FROM Employeesalary

--SUBQUERY IN PARTITION BY

SELECT EmoloyeeId,Salary,AVG(SALARY) OVER() AS ALLAVG
FROM Employeesalary

--SUBQUERY IN FROM
-- SUBQUERIES IS TIME CONSUMING
SELECT A.EmoloyeeId,ALLAVG
FROM (SELECT EmoloyeeId,Salary,AVG(SALARY)OVER () AS ALLAVG
	  FROM Employeesalary) A

--SUBQUERY IN WHERE

SELECT EmoloyeeId,Salary,Jobtitle
FROM Employeesalary
where Salary in (
SELECT * 
FROM Employeedemographics)