/*

TOPIC : TEMP TABLES

*/

CREATE TABLE #TEMP_EMPLOYEE(
EMPLOYEE_ID INT,
JOBTITLE VARCHAR(100),
SALARY INT
)

SELECT *
FROM #TEMP_EMPLOYEE

INSERT INTO #TEMP_EMPLOYEE VALUES
(1034,'HEAD',30000)

INSERT INTO #TEMP_EMPLOYEE
SELECT *
FROM SQL_Tutorial..Employeesalary


IF OBJECT_ID(N'tempdb..#TEMP_EMPLOYEE3') IS NOT NULL
BEGIN
DROP TABLE #TEMP_EMPLOYEE3
END
GO
CREATE TABLE #TEMP_EMPLOYEE3(
JOBTITLE varchar(50),
EMPLOYEperjob INT,
AVGAGE INT,
AVGSALARY INT
)

INSERT INTO #TEMP_EMPLOYEE3
SELECT Jobtitle,COUNT(Jobtitle),AVG(age),avg(Salary)
FROM SQL_Tutorial. .Employeedemographics DEMO
JOIN SQL_Tutorial. .Employeesalary SAL
	ON DEMO.EmployeeId=SAL.EmoloyeeId
group by Jobtitle

SELECT *
FROM #TEMP_EMPLOYEE3
SELECT *
FROM #TEMP_EMPLOYEE3


